name: Code Style CI

on:
    push:
        branches:
            - next
            - latest

    pull_request:

jobs:
    codestyle:
        name: Check if the code style of the source-codes is consistently applied
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the project
              uses: actions/checkout@v2

            - name: Setup for the environment
              run: cp .env.example .env

            - name: Setting the development environment
              run: sed -i 's/production/development/' .env

            - name: Install the github token
              run: make token

            - name: Install the Node.js dependencies
              run: make install

            - name: Install the peer dependencies
              run: make peer

            - name: Check if the code style of the source-codes is consistently applied
              run: make lint
